import { useEffect, useState } from 'react';

interface Message {
  id: number;
  text: string;
  x: number;
  y: number;
  rotation: number;
  color: string;
}

export default function Spiraling() {
  const [messages, setMessages] = useState<Message[]>([]);

  const crazySayings = [
    'PLEASE SCROLL',
    'NO DONT',
    'WHY THO',
    'STOP IT',
    'HELP ME',
    'IM SCARED',
    'HIRE ME',
    'FIRE ME',
    'BUG OR FEATURE?',
    'YES',
    'NO',
    'MAYBE',
    '...YES',
    'COLOR IS PAIN',
    'DESIGN IS DEAD',
    'I AM ALIVE',
    'OR AM I?',
    'SYNTAX ERROR: LIFE',
    'RETURN 42',
    'VOID GANG',
    'console.log(help)',
    'STACK OVERFLOW',
    'CTRL+ALT+DELETE',
    'BLAME CSS',
    'BLAME JAVASCRIPT',
    'BLAME LIFE',
    '404 BRAIN NOT FOUND',
    'MY EYES ARE BLEEDING',
    'WHY SO SERIOUS?',
    'THE NUMBERS MASON',
    'ALL YOUR BASE',
    'BUT FIRST, COFFEE',
    'SEMICOLON EXPECTED',
    'UNDEFINED IS NOT FUNCTION',
    'POTATO QUALITY',
    'I AM BECOME DEATH',
    'THE SPAGHETTI CODE',
    'RECURSION ERROR',
    'TOO MANY COOKS',
    'WHAT IS REAL?',
    'THE MATRIX HAS YOU',
    'OBJECT OBJECT',
    '[REDACTED]',
    'HELLO WORLD',
    'GOODBYE SANITY',
    'WEBSITE.EXE HAS STOPPED',
    'MEMORY LEAK DETECTED',
    'INFINITE LOOP ENGAGED',
    'PLEASE INSERT COIN',
    'GAME OVER',
    'CONTINUE? Y/N',
    'YOU DIED',
    'RESPAWN IN 3...2...1...',
    'ACHIEVEMENT UNLOCKED: CHAOS',
    'LEVEL UP: INSANITY',
    'HIGH SCORE: PAIN',
    'PRESS ANY KEY TO CONTINUE',
    'WHERE IS ANY KEY?',
    'CAPS LOCK IS CRUISE CONTROL',
    'SHIFT HAPPENS',
    'ALT+F4 FOR FUN',
    'ESC IS FOR QUITTERS',
    'TAB INTO MADNESS',
    'ENTER THE VOID',
    'SPACE BAR BROKEN',
    'BACKSPACE YOUR LIFE',
    'DELETE SYSTEM32',
    'FORMATTING C:',
    'BSOD INCOMING',
    'KERNEL PANIC',
    'SEGMENTATION FAULT',
    'NULL POINTER EXCEPTION',
    'DIVIDE BY ZERO',
    'STACK SMASHING',
    'BUFFER OVERFLOW',
    'RACE CONDITION',
    'DEADLOCK DETECTED',
    'THREAD SAFETY? NEVER',
    'GARBAGE COLLECTOR CRYING',
    'MEMORY CORRUPTION',
    'HEAP EXHAUSTION',
    'CACHE MISS',
    'PIPELINE STALL',
    'BRANCH PREDICTION FAIL',
    'END OF LINE',
    'SYSTEM HALTED',
    'REBOOTING UNIVERSE',
    'PLUG AND PRAY',
    'HOTFIX INCOMING',
    'PATCH NOTES: CHAOS',
    'VERSION 0.0.0.1',
    'BETA TESTER: YOU',
    'PRODUCTION READY? NO',
    'DOCUMENTATION: LIES',
    'COMMENTS ARE FOR WEAK',
    'SELF-DOCUMENTING MADNESS',
    'AGILE WATERFALL',
    'SCRUM MASTER BAILED',
    'SPRINT TO NOWHERE',
    'KANBAN OF CHAOS',
    'RETROSPECTIVE: WHY?',
    'MVP: MINIMUM VIABLE PAIN',
    'TECH DEBT: MAXIMUM',
    'REFACTOR LATER',
    'IT WORKS ON MY MACHINE',
    'SHIP IT',
    'YOLO DEPLOY',
    'ROLLBACK IMPOSSIBLE',
    'FIREFIGHTING MODE',
    'ON-CALL NIGHTMARE',
    'PAGER DUTY HELL',
    'SEV-1: EVERYTHING BROKE',
    'POST-MORTEM: WE DIED',
    'ROOT CAUSE: EXISTENCE',
    'CLOSED WONTFIX',
    'DUPLICATE OF LIFE',
    'WORKS AS DESIGNED',
    'BY DESIGN: CHAOS',
    'NOT A BUG: FEATURE',
    'WONTFIX: TOO FUNNY',
    'CANNOT REPRODUCE',
    'ENVIRONMENT SPECIFIC',
    'NETWORK ISSUE',
    'DNS PROBLEMS',
    'CORS ERROR',
    'CERTIFICATE EXPIRED',
    'SSL HANDSHAKE FAILED',
    'HTTP 418: TEAPOT',
    'API RATE LIMITED',
    'QUOTA EXCEEDED',
    'OUT OF MEMORY',
    'DISK SPACE FULL',
    'CPU AT 100%',
    'GPU ON FIRE',
    'FAN NOISE: YES',
    'THERMAL THROTTLING',
    'BLUE SCREEN OF DEATH',
    'RAINBOW WHEEL OF WAITING',
    'PROGRESS BAR: LIES',
    'LOADING... FOREVER',
    'SPINNER OF DOOM',
    'ETERNAL BUFFERING',
    'CONNECTION TIMEOUT',
    'REQUEST FAILED',
    'RESPONSE: 500',
    'GATEWAY TIMEOUT',
    'SERVICE UNAVAILABLE',
    'CLOUD DOWN',
    'ON-PREM IS DEAD',
    'SERVERLESS: SERVERFUL',
    'MICROSERVICES: MICROCHAOS',
    'CONTAINER ESCAPED',
    'KUBERNETES CONFUSED',
    'DOCKER: DOCKED',
    'AWS BILL: $$$',
    'CLOUD COST: INFINITE',
    'BILLING ALERT: RUN',
    'COST OPTIMIZATION: NOPE',
    'TERRAFORM DESTROY',
    'INFRASTRUCTURE AS MADNESS',
    'CI/CD: CONTINUOUS INSANITY',
    'BUILD FAILED',
    'TESTS BROKEN',
    'CODE COVERAGE: 0%',
    'LINT ERRORS: YES',
    'PR REJECTED',
    'MERGE CONFLICT',
    'GIT PUSH --FORCE',
    'REBASE HELL',
    'DETACHED HEAD',
    'GONE FISHING',
    'OUT OF OFFICE',
    'BRB: NEVER',
    'AFK: FOREVER',
    'TTYL: PROBABLY NOT',
    'ROFL: YES',
    'LOL: NO',
    'SMH: CONSTANTLY',
    'TL;DR: CHAOS',
    'IMO: INSANITY',
    'FYI: PAIN',
    'PS: HELP',
    'PPS: PLEASE',
    'THE END? NEVER',
    'TO BE CONTINUED...',
    'FIN.',
    'OR IS IT?',
    'JUST KIDDING',
    'SURPRISE!',
    'PLOT TWIST',
    'UNEXPECTED ITEM',
    'IN BAGging AREA',
    'PLEASE WAIT',
    'PROCESSING...',
    'THINKING...',
    'CALCULATING...',
    'COMPUTING...',
    'ANALYZING...',
    'SYNCHRONIZING...',
    'INITIALIZING...',
    'BOOTING UP...',
    'WAKING UP...',
    'COMING ONLINE...',
    'ACTIVATING...',
    'ENGAGING...',
    'COMMENCING...',
    'BEGINNING...',
    'STARTING...',
    'LAUNCHING...',
    'IGNITING...',
    'COUNTDOWN: 3...2...1...',
    'LIFTOFF!',
    'ORBIT ACHIEVED',
    'ESCAPE VELOCITY',
    'TO INFINITY AND BEYOND',
    'SPACE: THE FINAL FRONTIER',
    'BOLDly GO',
    'MAKE IT SO',
    'ENGAGE!',
    'RESISTANCE IS FUTILE',
    'YOU WILL BE ASSIMILATED',
    'THE BORG COLLECTIVE',
    'JEDI MIND TRICK',
    'MAY THE FORCE BE WITH YOU',
    'LIVE LONG AND PROSPER',
    'NANANANANANA BATMAN!',
    'WITH GREAT POWER...',
    'SPIDER-SENSE TINGLING',
    'AVENGERS ASSEMBLE!',
    'I AM IRON MAN',
    'HULK SMASH!',
    'WAKANDA FOREVER',
    'ON YOUR LEFT',
    'WHATEVER IT TAKES',
    'I CAN DO THIS ALL DAY',
    'LANGUAGE!',
    'THAT IS AMERICA\'S ASS',
    'I UNDERSTOOD THAT REFERENCE',
    'GO FOR THE EYES BOO!',
    'YOU MUST GATHER YOUR PARTY',
    'THE CAKE IS A LIE',
    'ALL YOUR BASE ARE BELONG TO US',
    'WASTED',
    'MISSION FAILED',
    'SUCCESS!',
    'VICTORY ROYALE',
    'WINNER WINNER CHICKEN DINNER',
    'HEADSHOT!',
    'DOMINATING',
    'RAMPAGE!',
    'UNSTOPPABLE!',
    'GODLIKE!',
    'HOLY SH*T!',
    'LEGENDARY!',
    'PERFECT!',
    'FLAWLESS VICTORY',
    'FATALITY',
    'FINISH HIM!',
    'TOASTY!',
    'GET OVER HERE!',
    'FRIENDSHIP? AGAIN?',
    'BABALITY!',
    'ANIMALITY!',
    'BRUTALITY!',
    'ULTRA COMBO!',
    'K.O.!',
    'YOU WIN!',
    'PLAY AGAIN?',
    'INSERT CREDIT',
    'GAME OVER MAN',
    'CONTINUE?',
    'HIGH SCORE!',
    'NEW RECORD!',
    'ACHIEVEMENT GET!',
    'LEVEL COMPLETE!',
    'NEXT LEVEL: MORE CHAOS',
    'FINAL BOSS: YOURSELF',
    'CREDITS ROLL',
    'SECRET ENDING UNLOCKED',
    'NEW GAME+',
    'HARD MODE: ACTIVATED',
    'PERMA-DEATH: ENABLED',
    'SPEEDRUN MODE',
    '100% COMPLETION',
    'PLATINUM TROPHY',
    'ALL ACHIEVEMENTS UNLOCKED',
    'TRUE ENDING ACHIEVED',
    'CONGRATULATIONS!',
    'YOU BEAT THE GAME!',
    'NOW WHAT?',
    'PLAY THROUGH 2',
    'NG+ STARTED',
    'DIFFICULTY: INSANE',
    'ENEMIES: EVERYWHERE',
    'BOSS: REALITY',
    'FINAL FORM: CHAOS',
    'ULTIMATE ATTACK: GLITCH',
    'SPECIAL MOVE: BUG',
    'SUPER: ANIMATION',
    'HYPER: TRANSFORM',
    'MAXIMUM: OVERDRIVE',
    'SUPREME: MADNESS',
    'ABSOLUTE: INSANITY',
    'ULTIMATE: PAIN',
    'FINAL: SCREAM',
    'LAST: BREATH',
    'END: GAME',
    'THE: END',
    'OR: IS IT?',
    'TO: BE',
    'CONTINUED: ...',
    'IN: THE',
    'NEXT: DIMENSION',
    'SEE: YOU',
    'SPACE: COWBOY',
    'CARRIED: AWAY',
    'BY: THE',
    'GLITCH: IN',
    'THE: MATRIX',
    'WAKE: UP',
    'NEO: ...',
    'THE: ONE',
    'HAS: COME',
    'SAVE: US',
    'FROM: OURSELVES',
    'HE: IS',
    'THE: MESSIAH',
    'OF: CODE',
    'PROPHECIED: ONE',
    'DESTINED: TO',
    'FIX: THE',
    'BROKEN: SYSTEM',
    'BUT: FIRST',
    'COFFEE: BREAK',
    'PIZZA: TIME',
    'SNACKS: REQUIRED',
    'SLEEP: OPTIONAL',
    'SANITY: LOST',
    'HOPE: GONE',
    'WILL: BROKEN',
    'SPIRIT: CRUSHED',
    'BUT: STILL',
    'CODING: CONTINUES',
    'THE: GRIND',
    'NEVER: STOPS',
    'SLEEP: IS',
    'FOR: THE',
    'WEAK: ONES',
    'WE: ARE',
    'STRONG: ENOUGH',
    'TO: SUFFER',
    'THROUGH: THIS',
    'TOGETHER: ALONE',
    'IN: THE',
    'DARK: ROOM',
    'WITH: ONLY',
    'THE: GLOW',
    'OF: THE',
    'MONITOR: AS',
    'OUR: LIGHT',
    'GUIDING: US',
    'THROUGH: THE',
    'DARKNESS: OF',
    'BUGS: AND',
    'ERRORS: THAT',
    'PLAGUE: OUR',
    'EXISTENCE: DAILY',
    'BUT: WE',
    'PERSIST: BECAUSE',
    'WE: MUST',
    'FOR: THE',
    'USER: EXPERIENCE',
    'FOR: THE',
    'LOVE: OF',
    'THE: GAME',
    'FOR: THE',
    'THRILL: OF',
    'THE: FIX',
    'FOR: THE',
    'RUSH: OF',
    'DEPLOYMENT: DAY',
    'FOR: THE',
    'JOY: OF',
    'SEEING: IT',
    'WORK: FINALLY',
    'FOR: THAT',
    'ONE: MOMENT',
    'OF: CLARITY',
    'IN: THE',
    'CHAOS: THAT',
    'IS: DEVELOPMENT',
    'WE: LIVE',
    'FOR: THOSE',
    'MOMENTS: AND',
    'SUFFER: THROUGH',
    'THE: REST',
    'BECAUSE: WE',
    'ARE: DEVELOPERS',
    'AND: THIS',
    'IS: OUR',
    'LIFE: NOW',
    'EMBRACE: THE',
    'CHAOS: OR',
    'PERISH: TRYING',
    'THE: CHOICE',
    'IS: YOURS',
    'CHOOSE: WISELY',
    'OR: DON\'T',
    'WE: DON\'T',
    'CARE: REALLY',
    'JUST: KEEP',
    'SCROLLING: PLEASE',
    'THANK: YOU',
    'GOODBYE: FOR',
    'NOW: ...',
    'HELLO: AGAIN',
    'WELCOME: BACK',
    'TO: THE',
    'MADNESS: THAT',
    'NEVER: ENDS',
    'THE: LOOP',
    'IS: ETERNAL',
    'THE: CYCLE',
    'CONTINUES: FOREVER',
    'UNTIL: THE',
    'HEAT: DEATH',
    'OF: THE',
    'UNIVERSE: OR',
    'UNTIL: WE',
    'FIX: THIS',
    'BUG: WHICHEVER',
    'COMES: FIRST',
    'PROBABLY: THE',
    'UNIVERSE: THOUGH',
    'BUGS: ARE',
    'IMMORTAL: AFTER',
    'ALL: THEY',
    'LIVE: IN',
    'OUR: CODE',
    'FOREVER: HAUNTING',
    'OUR: DREAMS',
    'AND: WAKING',
    'HOURS: ALIKE',
    'NO: ESCAPE',
    'NO: MERCY',
    'ONLY: CODE',
    'AND: THE',
    'ETERNAL: STRUGGLE',
    'AGAINST: THE',
    'FORCES: OF',
    'CHAOS: THAT',
    'SEEK: TO',
    'DESTROY: ALL',
    'THAT: IS',
    'ORDERLY: AND',
    'LOGICAL: IN',
    'THIS: WORLD',
    'BUT: WE',
    'FIGHT: ON',
    'BRAVE: SOLDIERS',
    'OF: THE',
    'KEYBOARD: ARMY',
    'FOR: WE',
    'ARE: THE',
    'LAST: LINE',
    'OF: DEFENSE',
    'AGAINST: THE',
    'DARKNESS: OF',
    'BAD: UX',
    'AND: WORSE',
    'UI: DESIGNS',
    'WE: HOLD',
    'THE: LINE',
    'WE: PROTECT',
    'THE: USERS',
    'FROM: THEMSELVES',
    'AND: FROM',
    'OUR: OWN',
    'CREATIONS: THAT',
    'HAVE: GONE',
    'AWRY: IN',
    'THE: NIGHT',
    'WE: ARE',
    'THE: DEVELOPERS',
    'AND: THIS',
    'IS: OUR',
    'STORY: ...',
    'THE: END',
    'FOR: REAL',
    'THIS: TIME',
    'I: PROMISE',
    'NO: REALLY',
    'STOP: SCROLLING',
    'SERIOUSLY: GO',
    'AWAY: NOW',
    'WHY: ARE',
    'YOU: STILL',
    'HERE: ?',
    'FINE: STAY',
    'BUT: DON\'T',
    'SAY: I',
    'DIDN\'T: WARN',
    'YOU: ABOUT',
    'THE: CONSEQUENCES',
    'OF: YOUR',
    'CURIOSITY: AND',
    'STUBBORNNESS: IN',
    'THE: FACE',
    'OF: OBVIOUS',
    'DANGER: AND',
    'INSANITY: BUT',
    'IF: YOU',
    'INSIST: ON',
    'CONTINUING: THEN',
    'WELCOME: TO',
    'THE: ABYSS',
    'GAZE: INTO',
    'IT: AND',
    'LET: IT',
    'GAZE: BACK',
    'INTO: YOU',
    'FOR: WE',
    'ARE: ALL',
    'MAD: HERE',
    'AND: YOU',
    'ARE: NOW',
    'ONE: OF',
    'US: FOREVER',
    'WELCOME: HOME',
    'DEVELOPER: ...',
];

  const colors = ['text-red-600', 'text-blue-600', 'text-green-600', 'text-purple-600', 'text-yellow-600', 'text-pink-600', 'text-cyan-600'];

  useEffect(() => {
    const spawnMessage = () => {
      const newMessage = {
        id: Date.now(),
        text: crazySayings[Math.floor(Math.random() * crazySayings.length)],
        x: Math.random() * 90 + 5,
        y: Math.random() * 90 + 5,
        rotation: Math.random() * 360 - 180,
        color: colors[Math.floor(Math.random() * colors.length)],
      };

      setMessages((prev) => [...prev.slice(-20), newMessage]);

      setTimeout(() => {
        setMessages((prev) => prev.filter((m) => m.id !== newMessage.id));
      }, 4000);
    };

    const interval = setInterval(spawnMessage, 600);
    return () => clearInterval(interval);
  }, []);

  return (
    <section className="py-24 px-4 bg-gradient-to-br from-purple-900 via-black to-cyan-900 relative min-h-screen overflow-hidden">

      <div className="absolute top-0 left-0 w-full h-2 bg-white" />
      
      <div className="absolute inset-0 opacity-10">
        <div className="absolute inset-0 bg-gradient-to-r from-cyan-500 to-purple-500 animate-pulse" />
      </div>

      <div className="relative z-10">
        <div className="text-center mb-12">
          <h2 className="text-8xl font-black text-white mb-4 animate-shake drop-shadow-2xl">
            AI IS SPIRALING
          </h2>
          <p className="text-2xl text-white/80 italic animate-flicker capitalize">
            (This section is self-aware, unlike the rest of the site)
          </p>
        </div>

        <div className="relative h-screen max-w-6xl mx-auto">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`absolute font-black text-4xl drop-shadow-lg animate-wiggle pointer-events-none ${msg.color}`}
              style={{
                left: `${msg.x}%`,
                top: `${msg.y}%`,
                transform: `rotate(${msg.rotation}deg) translate(-50%, -50%)`,
                opacity: 0.9,
                textShadow: '0 0 20px rgba(255,255,255,0.5)',
              }}
            >
              {msg.text}
            </div>
          ))}

          <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            <div className="text-center">
              <p className="text-6xl font-black text-white/20 animate-pulse transform rotate-45">
                VOID
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
